### ISSUE TITLE
Bug in LCDGOTO Function

### ISSUE THREAD

**Issue by ced9010** [gavinlyonsrepo/HD44780_LCD_PCF8574#1]
The function 'HD44780LCD::PCF8574_LCDGOTO'  sets the cursor to the desired position by calculating bitwise OR of the line address and the column number. This works well with the starting values of line one (0x80) and line 2 (0xC0) as well as the 16col values for line 3 (0x90) and line 4 (0xD0).
But for 20 column LCD the starting values for line 3 (0x94) and line 4 (0xD4) do not work.
The base values are correct, but the bitwise OR lead to wrong position.
Please see red marked cells in image for reference.
![LCDAddress_Bug](https://user-images.githubusercontent.com/66493205/163872765-385d063b-1bfa-4eb5-949d-80bc64957003.png)
I suggest using a simple addition the calculate the LCD ADDRESS.

**Comment by gavinlyonsrepo** [comment]
Hi 

Thanks for the information. 
It was only tested on a 16x02 part as that's all I had as per Readme.
I have a 20x04 part on the way with some other stuff and when that gets here I will 
test it and check out the issue.

Thanks

**Comment by gavinlyonsrepo** [comment]
Hi 

The part arrived.
Version 1.1.0 released with the bug for 20x04 fixed

Regards

**Comment by ced9010** [comment]
Thank you for cleaning this issue :)
