### ISSUE TITLE
for STM32 bluepill Connect SDA and SCL to B7 and B6 respectively

### ISSUE THREAD

**Issue by happymacer** [gavinlyonsrepo/HD44780_LCD_PCF8574#2]
for STM32 Connect SDA and SCL to B7 and B6 respectively (just saying as its not stated anywhere I could find).  Worked a treat thanks even on CKS32!

Is it possible to add a way to set the I2C port to use on the Bluepill?  It is done on the example I2C scanner so would be a nice addition.

**Comment by gavinlyonsrepo** [comment]
Hi 

The Pins used for other tested MCU's are in "extras/docs" folder in file  "GPIO_MCU_used.txt "
I mentioned this in readme. 

I will look into "Is it possible to add a way to set the I2C port to use on the Bluepill? " at some point.

regards

**Comment by gavinlyonsrepo** [comment]
Hi

Version 1.2.0 Released. Option added for User to pick I2C port for STM32 bluepill.
In example files comment in #define STM32_BLUE_PILL_SETUP and pick which port you want.

Regards
